server.port=8081
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true

# Database Configuration (H2)
spring.datasource.url=jdbc:h2:mem:maverickdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# H2 Console (http://localhost:8081/h2-console)
spring.h2.console.enabled=true

# JPA
spring.jpa.show-sql=true

# Logging
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
# Swagger / Open API
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Togglz
togglz.console.enabled=true
togglz.console.path=/togglz-console
togglz.console.secured=false
# Explicitly list the Enum class
# togglz.feature-enums=com.maverick.feature.config.AppFeatures
# Debug Logging
logging.level.org.togglz=DEBUG
